route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: 'telegram-bot'
receivers:
- name: 'telegram-bot'
  webhook_configs:
  - url: 'http://localhost:9087/alert'
