route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: 'notifications'
receivers:
- name: 'notifications'
  slack_configs:
  - api_url: 'https://localhost/'
    channel: '#prometheus'
